// Package blobman — the chunked-release manifest (v0.19.7+): a JSON
// description of one release tarball as fixed-size SHA-256-hashed chunks.
// It is generated by CI (cmd/genmanifest during release.yml), attached to
// the release as an ASSET, and fetched by `freens upgrade` FROM GITHUB
// ORIGIN (a few hundred kilobytes; the slow path is irrelevant). The
// manifest is the trust anchor for peer-served chunks: a peer's 48 KiB
// slice that does not reproduce its manifest hash is discarded and the
// peer is blacklisted — the manifest needs no signature because it
// arrives over the same TLS-to-origin channel as the download it
// replaces (signing it with a CI key is the separate "survive github
// compromise" upgrade, deliberately out of scope).
package blobman

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
)

// DefaultChunkSize balances two UDP realities: a chunk must fit ONE
// datagram (60 KiB rides just under the 64 KiB UDP ceiling inside a
// signed response, so every chunk is exactly one max-size round trip),
// and fewer, larger chunks mean fewer loss-exposed round trips and a
// 5x smaller manifest than the 48 KiB first cut. Lossy links retry per
// chunk; pipelined clients hide the latency.
const DefaultChunkSize = 60 * 1024

// Manifest describes one release tarball as hashed chunks. Chunks are
// ALIGNED: chunk i covers bytes [i*ChunkSize, min((i+1)*ChunkSize, Size)).
type Manifest struct {
	Tag       string   `json:"tag"`
	Asset     string   `json:"asset"`
	Size      int64    `json:"size"`
	ChunkSize int      `json:"chunk_size"`
	SHA256    string   `json:"sha256"` // the whole tarball (lowercase hex)
	Chunks    []string `json:"chunks"` // per-chunk SHA-256 (lowercase hex)
}

// Compute reads path and builds its manifest for tag/asset.
func Compute(path, tag, asset string) (*Manifest, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	m := &Manifest{Tag: tag, Asset: asset, ChunkSize: DefaultChunkSize}
	h := sha256.New()
	buf := make([]byte, m.ChunkSize)
	for {
		n, rerr := io.ReadFull(f, buf)
		if n > 0 {
			ch := sha256.Sum256(buf[:n])
			m.Chunks = append(m.Chunks, hex.EncodeToString(ch[:]))
			m.Size += int64(n)
			h.Write(buf[:n])
		}
		if rerr == io.EOF || rerr == io.ErrUnexpectedEOF {
			break
		}
		if rerr != nil {
			return nil, rerr
		}
	}
	m.SHA256 = hex.EncodeToString(h.Sum(nil))
	return m, nil
}

// Load parses a manifest file (the verb downloads the JSON bytes; Load is
// for tools and tests).
func Load(path string) (*Manifest, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return Parse(b)
}

// Parse decodes and validates manifest JSON bytes.
func Parse(b []byte) (*Manifest, error) {
	m := new(Manifest)
	if err := json.Unmarshal(b, m); err != nil {
		return nil, fmt.Errorf("blobman: %w", err)
	}
	if err := m.Validate(); err != nil {
		return nil, err
	}
	return m, nil
}

// Validate pins the invariants the chunk client relies on: the chunk list
// must exactly cover Size at ChunkSize granularity (a truncated or padded
// list would make the assembler accept a doctored file), sizes fit the
// transport, and the digests are well-formed hex.
func (m *Manifest) Validate() error {
	if m.ChunkSize <= 0 || m.ChunkSize > 64*1024 {
		return fmt.Errorf("blobman: chunk_size %d out of range", m.ChunkSize)
	}
	if m.Size <= 0 {
		return fmt.Errorf("blobman: empty asset")
	}
	want := int((m.Size + int64(m.ChunkSize) - 1) / int64(m.ChunkSize))
	if len(m.Chunks) != want {
		return fmt.Errorf("blobman: %d chunks for size %d at chunk_size %d, want %d", len(m.Chunks), m.Size, m.ChunkSize, want)
	}
	if !isHex64(m.SHA256) {
		return fmt.Errorf("blobman: bad sha256")
	}
	for i, c := range m.Chunks {
		if !isHex64(c) {
			return fmt.Errorf("blobman: chunk %d: bad digest", i)
		}
	}
	return nil
}

// ChunkLen is the byte length of chunk i (the last one is short).
func (m *Manifest) ChunkLen(i int) int64 {
	lo := int64(i) * int64(m.ChunkSize)
	if r := m.Size - lo; r < int64(m.ChunkSize) {
		return r
	}
	return int64(m.ChunkSize)
}

func isHex64(s string) bool {
	if len(s) != 64 {
		return false
	}
	_, err := hex.DecodeString(s)
	return err == nil
}
